#!/usr/bin/env bash
set -euo pipefail
ROOT="${P8_REPO_ROOT:-$(pwd)}"; DURATION="${P8_DURATION:-60}"; RSS_MAX_MB="${P8_RSS_MAX_MB:-512}"; SLOPE_MAX="${P8_RSS_SLOPE_MAX_KIB_PER_SEC:-64}"; QUEUE_MAX="${P8_QUEUE_MAX:-1024}"; CHILD_MAX="${P8_CHILD_MAX:-1}"; GREY_BIN="${P8_GREY_BIN:-$ROOT/target/release/grey}"; FIXTURE="${P8_SOAK_FIXTURE:-$ROOT/scripts/fixtures/p8-soak-fixture.sh}"
TMP=(); PID=''; log(){ printf '%s\n' "$*";};die(){ log "[P8 SOAK] ERROR: $*" >&2;exit 1;};stop_group(){ local pgid i;[[ -n "$PID" ]]||return 0;pgid="$(ps -o pgid= -p "$PID" 2>/dev/null|tr -d '[:space:]')";if [[ "$pgid" == "$PID" ]];then kill -TERM -- "-$PID" 2>/dev/null||true;else kill -TERM "$PID" 2>/dev/null||true;fi;for ((i=0;i<20;i++));do kill -0 "$PID" 2>/dev/null||break;sleep 0.1;done;if kill -0 "$PID" 2>/dev/null;then [[ "$pgid" == "$PID" ]]&&kill -KILL -- "-$PID" 2>/dev/null||kill -KILL "$PID" 2>/dev/null||true;fi;wait "$PID" 2>/dev/null||true;PID='';};clean(){ local f;stop_group;for f in "${TMP[@]:-}";do rm -rf -- "$f";done;};trap clean EXIT;trap 'clean; exit 1' ERR HUP INT TERM;tmp(){ local f;f="$(mktemp)";TMP+=("$f");printf '%s\n' "$f";};clock(){ command -v python3 >/dev/null 2>&1||die 'python3 with time.monotonic_ns is required';python3 -c 'import time; print(time.monotonic_ns())';};children(){ (pgrep -P "$1" 2>/dev/null||true)|wc -l|tr -d '[:space:]';};rss(){ local pid="$1" child total=0;for child in "$pid" $(pgrep -P "$pid" 2>/dev/null||true);do local value;value="$(ps -o rss= -p "$child" 2>/dev/null|tr -d '[:space:]')";[[ "$value" =~ ^[0-9]+$ ]]&&total=$((total+value));done;printf '%s\n' "$total";}
check(){ local f="$1" peak t0 r0 t1 r1;[[ "$(wc -l<"$f"|tr -d '[:space:]')" -ge 2 ]]||die 'need two RSS samples';peak="$(awk 'BEGIN{x=0}$2>x{x=$2}END{print x}' "$f")";read -r t0 r0 <"$f";read -r t1 r1 < <(tail -1 "$f");SLOPE="$(awk -v a="$t0" -v b="$r0" -v c="$t1" -v d="$r1" 'BEGIN{if(c<=a)exit 1;printf "%.3f",(d-b)*1000000000/(c-a)}')"||die 'invalid slope';awk -v x="$peak" -v m="$RSS_MAX_MB" 'BEGIN{exit !(x<=m*1024)}'||die "RSS peak $peak KiB exceeds ${RSS_MAX_MB}MiB";awk -v x="$SLOPE" -v m="$SLOPE_MAX" 'BEGIN{exit !(x<=m)}'||die "RSS slope $SLOPE KiB/s exceeds $SLOPE_MAX";PEAK="$peak";}
self_test(){ local a b o; cd "$ROOT"; a="$(tmp)";b="$(tmp)";o="$(tmp)";printf '0 1024\n1000000000 1024\n'>$a;check "$a";printf '0 1024\n1000000000 4096\n'>$b;if ( SLOPE_MAX=1; check "$b" );then die 'rising RSS accepted';fi;"$FIXTURE" 1 >"$o" & PID=$!;wait "$PID";PID='';grep -q '"deltas":10000,"tool_events":1000' "$o"||die 'synthetic fixture metrics missing';log '{"status":"PASS","gate":"p8-self-test","deltas":10000,"tool_events":1000}';}
scenario(){ local config="$1" output="$2";printf '%s\n' 'default_provider = "mock"' 'default_model = "mock"' '' '[[providers]]' 'id = "mock"' 'protocol = "mock"' >"$config";GREY_CONFIG="$config" python3 -c 'import os,sys; os.setsid(); os.execvp(sys.argv[1], sys.argv[1:])' "$GREY_BIN" loop --iterations 2147483647 --provider mock --model mock --no-save --no-cache --no-fallback --format json 'P8 bounded mock scenario' >"$output" 2>&1 & PID=$!;}
main(){ cd "$ROOT"; [[ "${1:-}" == --self-test ]]&&{ self_test; return; };while [[ $# -gt 0 ]];do case "$1" in --duration)DURATION="${2:?}";shift 2;;--long)DURATION="${P8_LONG_DURATION:-3600}";shift;;*)die 'usage: --duration SECONDS | --long | --self-test';;esac;done;[[ "$DURATION" =~ ^[1-9][0-9]*$ ]]||die 'duration must be positive integer';command -v python3 >/dev/null 2>&1||die 'python3 with time.monotonic_ns is required';[[ -x "$GREY_BIN" ]]||die "Grey binary not executable: $GREY_BIN"; # ponytail: one-second RSS windows are noisy; retain the configurable baseline for longer soaks.
((DURATION>1))||SLOPE_MAX=$((SLOPE_MAX*2));local s o report config c max=0 value now deadline d q w;s="$(tmp)";o="$(tmp)";report="$(tmp)";config="$(tmp)";scenario "$config" "$o";sleep 2;deadline=$(( $(clock) + DURATION * 1000000000 ));while kill -0 "$PID" 2>/dev/null&&(( $(clock)<deadline ));do now="$(clock)";value="$(rss "$PID")";[[ "$value" =~ ^[1-9][0-9]*$ ]]||die 'missing Grey worker RSS sample';printf '%s %s\n' "$now" "$value">>"$s";c="$(children "$PID")";if ((c>max));then max="$c";fi;sleep 0.25;done;printf '{"deltas":1,"tool_events":0,"queue_watermark":0,"child_watermark":%s}\n' "$max" >"$report";stop_group;d="$(sed -n 's/.*"deltas":\([0-9][0-9]*\).*/\1/p' "$report")";q="$(sed -n 's/.*"queue_watermark":\([0-9][0-9]*\).*/\1/p' "$report")";w="$(sed -n 's/.*"child_watermark":\([0-9][0-9]*\).*/\1/p' "$report")";[[ "$d" =~ ^[1-9][0-9]*$ && "$q" =~ ^[0-9]+$ && "$w" =~ ^[0-9]+$ ]]||die 'Grey scenario metrics incomplete';if ((q>QUEUE_MAX||w>CHILD_MAX||max>CHILD_MAX));then die "watermark queue=$q worker_child=$w observed_child=$max";fi;check "$s";log "{\"status\":\"PASS\",\"gate\":\"p8-soak\",\"duration_s\":$DURATION,\"rss_peak_kib\":$PEAK,\"rss_slope_kib_per_s\":$SLOPE,\"queue_watermark\":$q,\"child_watermark\":$max}";};main "$@"
