#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="${P6_REPO_ROOT:-$(pwd)}"; GREY_BIN="${P6_GREY_BIN:-$REPO_ROOT/target/release/grey}"
CARGO_BIN="${P6_CARGO_BIN:-rustup run 1.97.1 cargo}"; TIME_BIN="${P6_TIME_BIN:-/usr/bin/time}"
WARMUPS="${P6_STARTUP_WARMUPS:-1}"; REPEATS="${P6_STARTUP_REPEATS:-7}"; STARTUP_MAX_MS="${P6_STARTUP_MAX_MS:-300}"; MEMORY_MAX_MB="${P6_MEMORY_MAX_MB:-1024}"
RENDER_TEST="${P6_RENDER_TEST:-p6_render_pipeline_smoke_fps_baseline}"; SCAN_FILES="${P6_SCAN_FILES:-100000}"; SCAN_SUBDIRS="${P6_SCAN_SUBDIRS:-64}"; SCAN_MAX_MS="${P6_SCAN_MAX_MS:-5000}"
TMP=(); WATERMARK=0; CHILD_PID=''
log(){ printf '%s\n' "$*"; }; die(){ log "[P6 PERF] ERROR: $*" >&2; exit 1; }; clean(){ local f; if [[ -n "$CHILD_PID" ]]; then kill "$CHILD_PID" 2>/dev/null || true; wait "$CHILD_PID" 2>/dev/null || true; fi; for f in "${TMP[@]:-}"; do rm -rf -- "$f"; done; }; trap clean EXIT; trap 'clean; exit 1' ERR HUP INT TERM
tmp(){ local f; f="$(mktemp "$@")"; TMP+=("$f"); printf '%s\n' "$f"; }; child_count(){ (pgrep -P "$$" 2>/dev/null || true) | wc -l | tr -d '[:space:]'; }; children(){ local n; n="$(child_count)"; if ((n>WATERMARK)); then WATERMARK="$n"; fi; }
le(){ awk -v a="$1" -v b="$2" 'BEGIN {exit !(a<=b+.000001)}' || die "$3: $1 > $2"; }; ge(){ awk -v a="$1" -v b="$2" 'BEGIN {exit !(a+.000001>=b)}' || die "$3: $1 < $2"; }
detect_time(){ if "$TIME_BIN" -f 'real=%e rss=%M' true >/dev/null 2>&1; then MODE=gnu; elif "$TIME_BIN" -l true >/dev/null 2>&1; then MODE=bsd; else die 'GNU/BSD time required; refusing unmeasured fallback'; fi; }
elapsed(){ case "$MODE" in gnu) awk -F= '$1=="real"{x=$2} END{if(x=="")exit 1;print x}' "$1";; bsd) awk '$2=="real"{x=$1} END{if(x=="")exit 1;print x}' "$1";; esac; }
rss(){ case "$MODE" in gnu) awk -F= '$1=="rss"&&$2~/^[0-9]+$/{x=$2} END{if(x=="")exit 1;print x}' "$1";; bsd) awk '$2=="maximum"&&$3=="resident"&&$4=="set"&&$5=="size"&&$1~/^[0-9]+$/{x=$1/1024} END{if(x=="")exit 1;printf "%.0f\n",x}' "$1";; esac; }
run(){ local out timing sec mem status; out="$(tmp)"; timing="$(tmp)"; children; case "$MODE" in gnu) "$TIME_BIN" -f 'real=%e\nrss=%M' "$@" >"$out" 2>"$timing" &;; bsd) "$TIME_BIN" -l "$@" >"$out" 2>"$timing" &;; esac; CHILD_PID=$!; if wait "$CHILD_PID"; then status=0; else status=$?; fi; CHILD_PID=''; if ((status)); then cat "$out" "$timing" >&2; die 'benchmark command failed'; fi; children; sec="$(elapsed "$timing")" || die 'missing elapsed sample'; mem="$(rss "$timing")" || die 'missing RSS sample'; [[ "$sec" =~ ^[0-9]+([.][0-9]+)?$ && "$mem" =~ ^[0-9]+$ ]] || die 'invalid timing sample'; awk -v s="$sec" -v m="$mem" 'BEGIN{printf "%.3f %s\n",s*1000,m}'; }
median(){ sort -n | awk 'NR==4{print;exit}'; }
startup(){ local i ms mem all='' peak=0; [[ "$REPEATS" == 7 ]] || die 'P6_STARTUP_REPEATS must be exactly 7'; for ((i=0;i<WARMUPS;i++)); do run "$GREY_BIN" providers list >/dev/null; done; for ((i=1;i<=7;i++)); do read -r ms mem < <(run "$GREY_BIN" providers list); log "[startup-$i] ${ms}ms RSS=${mem}KiB"; all+="$ms\n"; if ((mem>peak)); then peak="$mem"; fi; done; ms="$(printf '%b' "$all"|median)"; mem="$(awk -v x="$peak" 'BEGIN{printf "%.2f",x/1024}')"; log "[startup] median=${ms}ms max_rss=${mem}MiB"; le "$ms" "$STARTUP_MAX_MS" 'startup median'; le "$mem" "$MEMORY_MAX_MB" 'startup RSS'; }
render(){ local out fps avg max; out="$(tmp)"; $CARGO_BIN test -p grey-tui "tests::$RENDER_TEST" -- --exact --ignored --nocapture >"$out" 2>&1 || { cat "$out"; die 'render benchmark failed'; }; fps="$(awk -F= '$1=="P6_RENDER_FPS"{x=$2}END{print x}' "$out")"; avg="$(awk -F= '$1=="P6_RENDER_AVG_MS"{x=$2}END{print x}' "$out")"; max="$(awk -F= '$1=="P6_RENDER_MAX_FRAME_MS"{x=$2}END{print x}' "$out")"; [[ -n "$fps" && -n "$avg" && -n "$max" ]] || die 'render metrics missing'; ge "$fps" "${P6_RENDER_FPS_MIN:-15}" 'render fps'; le "$avg" "${P6_RENDER_AVG_MS_MAX:-66}" 'render average'; le "$max" "${P6_RENDER_MAX_FRAME_MS_MAX:-1000}" 'render max'; }
scan(){ local root i n ms mem; root="$(tmp -d)"; for ((i=1;i<=SCAN_FILES;i++));do mkdir -p "$root/$((i%SCAN_SUBDIRS))"; : >"$root/$((i%SCAN_SUBDIRS))/$i";done; n="$(find "$root" -type f|wc -l|tr -d '[:space:]')"; [[ "$n" == "$SCAN_FILES" ]]||die "scan fixture count $n"; read -r ms mem < <(run find "$root" -type f -print0); log "[scan] ${ms}ms RSS=${mem}KiB"; le "$ms" "$SCAN_MAX_MS" 'scan latency'; }
self_test(){ local g b z; cd "$REPO_ROOT"; g="$(tmp)";b="$(tmp)";z="$(tmp)";printf 'real=0.125\nrss=2048\n'>$g;MODE=gnu;[[ "$(elapsed "$g")" == 0.125 && "$(rss "$g")" == 2048 ]]||die 'GNU parsing';printf '0.12 real\n             2097152  maximum resident set size\n'>$b;MODE=bsd;[[ "$(elapsed "$b")" == 0.12 && "$(rss "$b")" == 2048 ]]||die 'BSD bytes→KiB';: >$z;! rss "$z" >/dev/null 2>&1||die 'missing RSS accepted';[[ "$(printf '7\n1\n4\n2\n6\n3\n5\n'|median)" == 4 ]]||die 'median';log '{"status":"PASS","gate":"p6-self-test","samples":7}'; }
main(){ cd "$REPO_ROOT"; [[ "${1:-}" == --self-test ]]&&{ self_test;return;};[[ -x "$GREY_BIN" ]]||die "$GREY_BIN not executable";detect_time;startup;render;scan;log "{\"status\":\"PASS\",\"gate\":\"p6-perf\",\"child_watermark\":$WATERMARK}";};main "$@"
